name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud --quiet auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/$GCP_PROJECT/my-react-app .
          docker push gcr.io/$GCP_PROJECT/my-react-app
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-react-app \
            --image gcr.io/$GCP_PROJECT/my-react-app \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          REGION: ${{ secrets.GCP_REGION }}
